#!/usr/bin/env python3
"""Generate a `partition-scenarios` overlay from a topology's
country-code metadata.

Until predicate selectors land (Phase 3), the sim-rs partition selector
takes explicit node-name lists.  This script reads the topology's
`*.yaml.meta.json` sidecar (which carries a per-node `cc` country code),
buckets nodes into continents, and emits a `set-to-set` partition that
cuts every edge crossing the chosen boundary — e.g. EU ↔ NA.

The emitted YAML is a parameter overlay: pass it to sim-cli as the LAST
`-p` so it layers on top of the experiment config.

    python3 scripts/gen-partition.py \
        ../data/simulation/pseudo-mainnet/topology-v4-mainnet.yaml \
        --from EU --to NA --start 300 --stop 900 -o /tmp/eu-na.yaml

    cargo run --release -- <topology> out.jsonl -s 1000 \
        -p <experiment-config>.yaml -p /tmp/eu-na.yaml

Node names are resolved against the topology at sim init, and the
selector's cartesian product is intersected with the edges that actually
exist, so only real cross-boundary links are cut.  The true cut-edge
count is reported at runtime in the `PartitionStarted` telemetry.
"""

import argparse
import json
import os
import sys

# ISO 3166-1 alpha-2 → coarse continent bucket.  Transcontinental cases
# follow the common networking convention (RU→EU, TR→AS).  Override with
# --from-cc / --to-cc when a different split is wanted.
CONTINENT = {
    # Europe
    "AT": "EU", "BE": "EU", "BG": "EU", "CH": "EU", "CY": "EU", "CZ": "EU",
    "DE": "EU", "DK": "EU", "EE": "EU", "ES": "EU", "FI": "EU", "FR": "EU",
    "GB": "EU", "GR": "EU", "HR": "EU", "HU": "EU", "IE": "EU", "IS": "EU",
    "IT": "EU", "LI": "EU", "LT": "EU", "LU": "EU", "LV": "EU", "MT": "EU",
    "NL": "EU", "NO": "EU", "PL": "EU", "PT": "EU", "RO": "EU", "RS": "EU",
    "RU": "EU", "SE": "EU", "SI": "EU", "SK": "EU", "UA": "EU",
    # North America (incl. Caribbean / Central America)
    "CA": "NA", "CW": "NA", "MX": "NA", "US": "NA", "CR": "NA", "PA": "NA",
    # South America
    "AR": "SA", "BO": "SA", "BR": "SA", "CL": "SA", "CO": "SA", "PE": "SA",
    "UY": "SA", "VE": "SA",
    # Asia
    "AE": "AS", "CN": "AS", "HK": "AS", "ID": "AS", "IL": "AS", "IN": "AS",
    "IR": "AS", "JP": "AS", "KR": "AS", "MY": "AS", "PH": "AS", "SA": "AS",
    "SG": "AS", "TH": "AS", "TR": "AS", "TW": "AS", "VN": "AS",
    # Oceania
    "AU": "OC", "NC": "OC", "NZ": "OC",
    # Africa
    "EG": "AF", "KE": "AF", "NG": "AF", "ZA": "AF",
}


def meta_path(topology_path):
    """Resolve the sidecar path: accept either the topology .yaml or the
    .meta.json directly."""
    if topology_path.endswith(".meta.json"):
        return topology_path
    candidate = topology_path + ".meta.json"
    if os.path.exists(candidate):
        return candidate
    sys.exit(f"error: no metadata sidecar found at {candidate!r}")


def bucket_nodes(meta, from_set, to_set, by_cc):
    """Return (from_names, to_names, skipped) sorted by node index."""

    def keyfn(name):
        # node-12 → 12 for natural numeric ordering
        suffix = name.rsplit("-", 1)[-1]
        return (int(suffix) if suffix.isdigit() else 0, name)

    def classify(cc):
        if by_cc:
            return cc  # raw country code
        return CONTINENT.get(cc, "??") if cc else "??"

    from_names, to_names, skipped = [], [], 0
    for name, info in meta.items():
        group = classify(info.get("cc"))
        if group in from_set:
            from_names.append(name)
        elif group in to_set:
            to_names.append(name)
        else:
            skipped += 1
    from_names.sort(key=keyfn)
    to_names.sort(key=keyfn)
    return from_names, to_names, skipped


def emit_yaml(args, from_names, to_names):
    lines = []
    lines.append(f"# Generated by gen-partition.py")
    if args.isolate:
        # COMPLETE partition: cut every edge between the --from group and ALL
        # other nodes (the sim computes the complement), so there is no bridge
        # population left to relay across the cut.
        lines.append(f"# isolate={args.from_group} ({len(from_names)} nodes) from everyone else")
        lines.append("partition-scenarios:")
        lines.append(f"  - name: {args.name}")
        lines.append(f"    selector:")
        lines.append(f"      kind: isolate")
        lines.append(f"      direction: {args.direction}")
        lines.append(f"      nodes:")
        lines.extend(f"        - {n}" for n in from_names)
    else:
        lines.append(f"# from={args.from_group} ({len(from_names)} nodes)  "
                     f"to={args.to_group} ({len(to_names)} nodes)")
        lines.append("partition-scenarios:")
        lines.append(f"  - name: {args.name}")
        lines.append(f"    selector:")
        lines.append(f"      kind: set-to-set")
        lines.append(f"      direction: {args.direction}")
        lines.append(f"      from:")
        lines.extend(f"        - {n}" for n in from_names)
        lines.append(f"      to:")
        lines.extend(f"        - {n}" for n in to_names)
    lines.append(f"    start-time-s: {args.start}")
    if args.stop is not None:
        lines.append(f"    stop-time-s: {args.stop}")
    return "\n".join(lines) + "\n"


def parse_group_codes(s):
    """Split a comma-separated --from/--to value into a set of upper-cased
    codes, tolerating surrounding whitespace and empty tokens (e.g.
    "EU, NA" or a trailing comma "EU,")."""
    return {tok.strip() for tok in s.upper().split(",") if tok.strip()}


def main():
    p = argparse.ArgumentParser(
        description="Emit a partition-scenarios overlay from topology cc metadata.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("topology", help="topology .yaml (or its .meta.json sidecar)")
    p.add_argument("--from", dest="from_group", default="EU",
                   help="source group: continent code(s) or, with --by-cc, "
                        "country code(s); comma-separated (default: EU)")
    p.add_argument("--to", dest="to_group", default="NA",
                   help="target group (default: NA); ignored with --isolate")
    p.add_argument("--isolate", action="store_true",
                   help="COMPLETE partition: cut the --from group off from ALL "
                        "other nodes (no bridge), instead of just from --to")
    p.add_argument("--by-cc", action="store_true",
                   help="interpret --from/--to as raw country codes, not continents")
    p.add_argument("--name", default="eu-na-split", help="scenario name (telemetry)")
    p.add_argument("--start", type=float, default=300.0, help="start-time-s (default 300)")
    p.add_argument("--stop", type=float, default=None,
                   help="stop-time-s (omit to persist to end of sim)")
    p.add_argument("--direction", choices=["both", "from-to", "to-from"],
                   default="both", help="cut direction (default both)")
    p.add_argument("-o", "--out", help="write to file (default: stdout)")
    args = p.parse_args()

    from_set = parse_group_codes(args.from_group)
    to_set = parse_group_codes(args.to_group) if not args.isolate else set()
    if from_set & to_set:
        sys.exit(f"error: --from and --to overlap: {from_set & to_set}")

    with open(meta_path(args.topology)) as f:
        meta = json.load(f)

    from_names, to_names, skipped = bucket_nodes(meta, from_set, to_set, args.by_cc)
    if not from_names or (not args.isolate and not to_names):
        sys.exit(f"error: empty side (from={len(from_names)}, to={len(to_names)}); "
                 f"check --from/--to against the topology's country codes")
    # With --isolate the "other" side is the complement of --from.  If --from
    # already covers every node the complement is empty: the cut has nothing to
    # sever, so the overlay would be a silent no-op.  Fail loudly instead.
    if args.isolate and len(from_names) >= len(meta):
        sys.exit(f"error: --isolate --from {args.from_group} matches all "
                 f"{len(meta)} nodes; the complement is empty (no-op partition)")

    text = emit_yaml(args, from_names, to_names)
    if args.out:
        with open(args.out, "w") as f:
            f.write(text)

    if args.isolate:
        print(
            f"isolate {args.from_group}: {len(from_names)} nodes vs "
            f"{len(meta) - len(from_names)} others (COMPLETE partition, no bridge)\n"
            f"(runtime telemetry reports the actual cut-edge count)",
            file=sys.stderr,
        )
    else:
        print(
            f"from={args.from_group}: {len(from_names)} nodes | "
            f"to={args.to_group}: {len(to_names)} nodes | "
            f"unclassified/excluded: {skipped} (these BRIDGE the cut — not a complete partition)\n"
            f"(runtime telemetry reports the actual cross-boundary edge count)",
            file=sys.stderr,
        )
    if args.out:
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
